import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AppProvider from "@/components/providers/AppProvider";
import { Toaster } from "@/components/ui/toaster";
import MobileNav from "@/components/offMenu/MobileNav";
import ProgressBarProvider from "@/components/providers/ProgressBarProvider";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kukus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${monaSans.variable} antialiased overflow-x-hidden`}
      >
        <AppProvider>
          <ProgressBarProvider>
            {children}
            <Toaster />
            <MobileNav />
          </ProgressBarProvider>
        </AppProvider>
      </body>
    </html>
  );
}
